gitlab_external_url: "http://192.168.127.129:8081"
gitlab_ssh_port: 22
gitlab_dependencies:
  - curl
  - openssh-server
  - ca-certificates
  - tzdata

gitlab_package_name: gitlab-ce
gitlab_config_file: "/etc/gitlab/gitlab.rb"
gitlab_host: "192.168.127.129:8081"
gitlab_ctl_command: "gitlab-ctl"
